### ISSUE TITLE
Empty values for background property

### ISSUE THREAD

**Issue by NicolasJEngler** [LukyVj/colofilter.css#12]
Hi there,

Super thrilled to use these blendmodes. Just one thing I noticed, there are several background properties without a proper value set (see lines _171, 185, 189, 205, 209, 230, 234, and 237_ of **styles/colofilter.css**). This is most likely happening due to the lack of definition for some values in the Sass map of **styles/colofilter.scss**.

I would gladly create a pull request to mend this, but I'm a little lost on what values should go there.

**Comment by LukyVj** [comment]
Hi @NicolasJEngler !

Thanks for opening the issue!
Yeah, you're right, and it's because of the [`$color-map`](https://github.com/LukyVj/colofilter.css/blob/master/styles/colofilter.scss#L10-L13) values for the gradients. 

I had to keep them empty. And so, when compiled, it will write them with an empty value. 

Thanks for your issue, I'm about to fix that!

**Comment by LukyVj** [comment]
Fixed in https://github.com/LukyVj/colofilter.css/commit/11b93c7170f19da1f087f7b31a7b647f93a4f7e2

Thank you again!

**Comment by NicolasJEngler** [comment]
Don't mention it, thank _you_!
