### ISSUE TITLE
Weird class selectors - Why Using CSS Attributes selector

### ISSUE THREAD

**Issue by pmaxhogan** [LukyVj/colofilter.css#21]
You use `[class^="something"]` instead of `.something` in your CSS selectors. Why?

**Comment by LukyVj** [comment]
So, first of all, thanks for opening the issue.

You have to know that those "weird" class selectors, are called "CSS Attribute selectors".
Basically, it's, as the name explains, selecting elements with their attributes, and not their classes or tag name.

For the question : "Why do I do this" 
It's simple, as you pasted here `[class^="something"]`, the `^` is a css regex, and mean "If the class starts by `something`".

So in the end, it doesn't change anything on the html side, you'll write the colofilter classes normally, but for more flexibility codewise, I prefer using attribute selector. 

__So, let's take the line 15 of colofilter.scss__:
( https://github.com/LukyVj/colofilter.css/blob/master/styles/colofilter.scss#L15 ) 
`[class^="blend"]` == If the class is starting by `blend`.

__Line 41__ : 
( https://github.com/LukyVj/colofilter.css/blob/master/styles/colofilter.scss#L41 )
`&[class*="-dark"] {` == And contains `-dark` anywhere in the class ( `*` is used to target some content in an attribute, no matter it's position ) 

So literally, what those lines are doing is : 
`If the class is starting by BLEND and contains a -DARK class`.

Soo, in the end, with the compiled CSS, you can have rules like : 
```scss
[class^="blend"][class*="-red"][class*="-light"]
``` 
Which is self explainatory : __If the element class starts by "blend" and got the class "-red" and "-light"__

------ 
Obviously, I could have used a more verbose way of doing it, or any other naming system, but I picked this one, because it makes sense to me. 

More about "CSS Attributes selector" : https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by pmaxhogan** [comment]
Oh. That's cool. Makes sense. I've used CSS attribute selectors, but never seen them used for this.
